### ISSUE TITLE
OSX support?

### ISSUE THREAD

**Issue by yhslai** [leonid-shevtsov/headless#31]
On `ubuntu` you can install `xvfb` by `apt-get install`. On `OSX`, the `xvfb` is inclued in `XQuartz`. Though I have installed `XQuartz`, the headless gem still doesn't work:

```
Headless::Exception: Xvfb not found on your system
```

How to tell `Headless` where is my `xvfb`?

**Comment by daluu** [comment]
For those pointing out xvfb issue for FF and Chrome on Mac (for Selenium, etc.), you may need to find an x11 build/version of FF (and/or Chrome, but for Mac?), not the standard OS binary/install. This old article is one reference: http://afitnerd.com/2011/09/06/headless-browser-testing-on-mac/

**Comment by charleshuang80** [comment]
Using Mac OS X El Capitan. I had installed the latest XQuartz 2.7.9, and when running my tests kept getting `Xvfb is frozen (Headless::Exception)`. I looked all over for fixes to no avail (and this issue page kept popping up in my searches), and just couldn't get xvfb to run. Finally, I came across this post https://discussions.apple.com/thread/7590534?start=0&tstart=0. So I uninstalled XQuartz 2.7.9 (https://xquartz.macosforge.org/trac/wiki/X11-UsersFAQ#UninstallSnowLeopardorLater), and installed XQuartz 2.7.8, and running my tests ran without any errors from headless.

**Comment by molfar** [comment]
is there any fallback for mac os? Just to skip xvfb requirement, without no code change

**Comment by another-dave** [comment]
> FYI, for those pointing out xvfb issue for FF and Chrome on Mac (for Selenium, etc.), you may need to find an x11 build/version of FF (and/or Chrome, but for Mac?), not the standard OS binary/install. This old article is one reference: http://afitnerd.com/2011/09/06/headless-browser-testing-on-mac/

For reference, this is now at http://old.afitnerd.com/2011/09/06/headless-browser-testing-on-mac/
