### ISSUE TITLE
Occasional 'unable to obtain stable firefox connection' Error

### ISSUE THREAD

**Issue by tfillmore-ck** [leonid-shevtsov/headless#45]
When attempting to run selenium webdriver tests with the headless gem (v1.0.1) on CentOS, we are seeing tests fail with the following message around ~5% of the time on our CI server:
`unable to obtain stable firefox connection in 60 seconds`

This seems very similar to the issue detailed in this closed ticket, and the more recent comments indicate that other people are seeing this problem as well. https://github.com/leonid-shevtsov/headless/issues/33

When running with debug output we also see this error occur before the firefox timeout:
```The application 'firefox' lost its connection to the display :1785.0;
most likely the X server was shut down or you killed/destroyed
the application.```

Our tests should not be doing anything that would stop or restart the X server directly, as they are only accessing Xvfb through the headless gem. We are out of ideas to debug this issue, any information you might be able to provide would be greatly appreciated.

Full debug output can be seen here:
https://gist.github.com/tfillmore-ck/fcb534384752193ad4bd

**Comment by leonid-shevtsov** [comment]
Closing this for old age (and sorry for not looking into it earlier!) - please reopen if you have any current issues.
