### ISSUE TITLE
draw_mouse 0 not working

### ISSUE THREAD

**Issue by atzorvas** [leonid-shevtsov/headless#63]
Hi,

I would like to hide the mouse, but this seems "hard".
"draw_mouse 0" doesn't work as an option

any idea?

    ffmpeg version 2.7.2 Copyright (c) 2000-2015 the FFmpeg developers
      built with gcc 5.2.0 (GCC)
      configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gnutls --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-shared --enable-version3 --enable-x11grab
      libavutil      54. 27.100 / 54. 27.100
      libavcodec     56. 41.100 / 56. 41.100
      libavformat    56. 36.100 / 56. 36.100
      libavdevice    56.  4.100 / 56.  4.100
      libavfilter     5. 16.101 /  5. 16.101
      libavresample   2.  1.  0 /  2.  1.  0
      libswscale      3.  1.101 /  3.  1.101
      libswresample   1.  2.100 /  1.  2.100
      libpostproc    53.  3.100 / 53.  3.100
    Input #0, x11grab, from ':99':
      Duration: N/A, start: 1439194295.218890, bitrate: N/A
        Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1280x1024, 30 fps, 30 tbr, 1000k tbn, 30 tbc
    [NULL @ 0x55ebccdeff20] Unable to find a suitable output format for 'draw_mouse'
    draw_mouse: Invalid argument

**Comment by atzorvas** [comment]
found the error, this extra option should be provided as an option for the
 -i 

working example: https://github.com/atzorvas/headless/commit/9da26bd30f710596117642c33fc966a5fb7605d6

after I'll finish my task, I'll change this in order to be programmed right and I'll try a PR :)

**Comment by leonid-shevtsov** [comment]
So the `extra` options are misplaced? Maybe it's enough to move them to someplace earlier in the command line?

**Comment by atzorvas** [comment]
it's not enought, we need different extra options
for example :extra_i = [...], that will be placed right after -i command

or more easily/generaly, 
:extra = { i: [...] }

**Comment by leonid-shevtsov** [comment]
Fixed in version 2.3.0
