### ISSUE TITLE
how to set screen size?

### ISSUE THREAD

**Issue by atzorvas** [leonid-shevtsov/headless#64]
I need a bigger screen size for my browser, how to do that?
thanks

**Comment by atzorvas** [comment]
done, closing this :)
      @headless = Headless.new(:dimensions => '1920x1080x24')
      browser.window.resize_to(1920, 1080) # watir browser

**Comment by abderrahmanesaad** [comment]
@atzorvas how did you managed to do that i did what you said but screen shift ti the right can you explain
