### ISSUE TITLE
video recording with audio

### ISSUE THREAD

**Issue by atzorvas** [leonid-shevtsov/headless#66]
here is a "dirty" commit just to get the job done asap.

do we need audio recording? I find it usefull, well at least for the particular use case of mine

https://github.com/atzorvas/headless/commit/f8cc361bfe6b52167302080ae82df0384057fac0

**Comment by leonid-shevtsov** [comment]
But this can be accomplished with the `:extra` recorder option, as in

```ruby
Headless.new(video: { extra: %w(-acodec libmp3lame -ar 44100 -ab 128k -threads 0) }
```

Closing since it's been a year, please reopen if you have any questions.
