### ISSUE TITLE
consistently 'Unable to Obtain a Stable firefox connection in 60 seconds' on Debian 8

### ISSUE THREAD

**Issue by lloeki** [leonid-shevtsov/headless#67]
Currently setting up some CI runner on Debian 8, the following test fails (both with Debian's iceweasel and Mint's firefox):

```ruby
require 'headless'
require 'selenium-webdriver'

Headless.ly do
  driver = Selenium::WebDriver.for :firefox
  driver.navigate.to 'http://google.com'
  puts driver.title 
end
```

The same works on OS X. Using ruby 2.2, selenium-webdriver 2.47.1, headless 2.2, firefox 39 and 40. Firefox has been tested to work by itself by running it manually in Xvfb and capturing screen with imagemagick's import.

**Comment by lloeki** [comment]
There seems to be no issue with the official Firefox 40 binary tarball from Mozilla.

**Comment by lloeki** [comment]
Spoke too soon, errors are back.

**Comment by samnissen** [comment]
@lloeki Can you post the stack trace?

**Comment by leonid-shevtsov** [comment]
Closing this due to old age, I hope that upgrades to Selenium or Firefox got this issue sorted out.

Sorry for not looking into it earlier. If you still have the problem please reopen the issue and i will look into it promptly.
