### ISSUE TITLE
fatal IO error 11

### ISSUE THREAD

**Issue by atzorvas** [leonid-shevtsov/headless#68]
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":99"  
    after 908 requests (908 known processed) with 0 events remaining.

Video can't close & save properly because of this.
I'm able to run the same script with success in archlinux, but not with an ubuntu setup.
allthough I haven't setup the ubuntu machine, so maybe there is something getting in the way.

and idea?

**Comment by leonid-shevtsov** [comment]
Sounds like a bug in xvfb, especially if it only repros on Ubuntu. Googling reveals many different reasons for this error, that are not headless-related.

(Sorry for not looking into this earlier.)
