### ISSUE TITLE
Headless gem lacks global read permissions

### ISSUE THREAD

**Issue by NfNitLoop** [leonid-shevtsov/headless#74]
When I 'gem install headless', I get a gem that's installed that only has root with read/write permissions.

See: 
~~~
root@vagrant-ubuntu-trusty-64:/usr/local/rvm/gems/ruby-2.1.2/gems# find headless* -name "*.rb" -exec ls -lh {} ";"
-rw-r--r-- 1 root rvm 1.7K Dec 23 11:59 headless-1.0.2/lib/headless/video/video_recorder.rb
-rw-r--r-- 1 root rvm 1.5K Dec 23 11:59 headless-1.0.2/lib/headless/cli_util.rb
-rw-r--r-- 1 root rvm 5.1K Dec 23 11:59 headless-1.0.2/lib/headless.rb
-rw-r--r-- 1 root rvm 5.1K Dec 23 11:59 headless-1.0.2/spec/headless_spec.rb
-rw-r--r-- 1 root rvm 2.4K Dec 23 11:59 headless-1.0.2/spec/video_recorder_spec.rb

# vs:
-rw-r--r-- 1 root rvm 2.7K Dec 23 12:00 headless-2.2.0/lib/headless/video/video_recorder.rb
-rw------- 1 root rvm 1.6K Dec 23 12:00 headless-2.2.0/lib/headless/cli_util.rb
-rw------- 1 root rvm 7.0K Dec 23 12:00 headless-2.2.0/lib/headless.rb
-rw-r--r-- 1 root rvm 1.3K Dec 23 12:00 headless-2.2.0/spec/integration_spec.rb
-rw------- 1 root rvm 8.8K Dec 23 12:00 headless-2.2.0/spec/headless_spec.rb
-rw-r--r-- 1 root rvm 3.8K Dec 23 12:00 headless-2.2.0/spec/video_recorder_spec.rb
~~~

When I try to `require 'headless'`, I get the error: 

~~~
LoadError: cannot load such file -- headless
~~~

If I add read permissions to the file, I am able to load the module without error.

**Comment by leonid-shevtsov** [comment]
This is an issue with your rvm setup, not with headless specifically.

**Comment by NfNitLoop** [comment]
That's very likely the case. I'm a bit of a Ruby newbie. But it only seems to be happening with the headless 2.2.0 gem, and none of the dozens of other gems I have installed, or even the 1.0.2 gem. 

I can remove and reinstall both of those gems and the same problem happens.

**Comment by xvonabur** [comment]
I don't think rvm is an issue here. I have the same problem in production mode on Ubuntu 14.04. No rvm, rbenv or something like that. Pure ruby interpeter (2.2.4 in my case). BTW, I'm deploying with capistrano 3 and all other gems has right permissions. All, except headless gem.

**Comment by genegc** [comment]
I'm seeing this same problem on Ubuntu 14.04, ruby 2.1.1, no rvm. I reverted back to headless 1.0.2

**Comment by erkki** [comment]
can confirm a repro, looking at this now

**Comment by erkki** [comment]
the gem needs to be yanked and released with proper permissions, this is what's in the currently baked gem:
-rw-r--r--  0 wheel  wheel      27  5 aug    2015 .gitignore
-rw-r--r--  0 wheel  wheel     159  5 aug    2015 .travis.yml
-rw-r--r--  0 wheel  wheel    1943  5 aug    2015 CHANGELOG
-rw-r--r--  0 wheel  wheel      91  5 aug    2015 Gemfile
-rw-r--r--  0 wheel  wheel    1076  5 aug    2015 LICENSE
-rw-------  0 wheel  wheel    6654  5 aug    2015 README.md
-rw-r--r--  0 wheel  wheel      28  5 aug    2015 Rakefile
-rw-r--r--  0 wheel  wheel     638  5 aug    2015 headless.gemspec
-rw-------  0 wheel  wheel    7150  5 aug    2015 lib/headless.rb
-rw-------  0 wheel  wheel    1584  5 aug    2015 lib/headless/cli_util.rb
-rw-r--r--  0 wheel  wheel    2698  5 aug    2015 lib/headless/video/video_recorder.rb
-rw-------  0 wheel  wheel    8937  5 aug    2015 spec/headless_spec.rb
-rw-r--r--  0 wheel  wheel    1248  5 aug    2015 spec/integration_spec.rb
-rw-r--r--  0 wheel  wheel    3880  5 aug    2015 spec/video_recorder_spec.rb

**Comment by leonid-shevtsov** [comment]
@erkki thanks so much for the investigation! 

I've pushed version 2.2.2 which has read permissions for group and world for all files. Let me know if that works.

I'm not yanking the current version as it works fine for per-user installs.

**Comment by erkki** [comment]
@leonid-shevtsov thanks for the quick reply, confirmed, 2.2.2 works :)
