### ISSUE TITLE
import: unable to open X server `localhost:100' @ error/import.c/ImportImageCommand/364.

### ISSUE THREAD

**Issue by DmitryXO** [leonid-shevtsov/headless#89]
I have a fresh install selenium/ff/chrome/ruby/imagemagick and I get this error on headless.take_screenshot

**Comment by GPif** [comment]
Same issue on linux Kubuntu 17;04

it seems to be because of the way import is call :

```ruby
system "#{CliUtil.path_to('import')} -display localhost:#{display} -window root #{file_path}"
```

the presence of 'localhost' trigger this error

**Comment by ronaldsalas** [comment]
Any updates on this? I'm also experiencing a similar issue on a new Ubuntu 14 and I have no clue where to start investigating. We're on cucumber, with ImageMagick, Rails, Selenium, Chrome.
