### ISSUE TITLE
Running headless with flash

### ISSUE THREAD

**Issue by richlewis14** [leonid-shevtsov/headless#93]
Hi

Not sure if this is the best place for this if not apologies. When using headless I can run chrome fine, take screenshots etc. I face an issue though when I try to open a page that needs flash to run.

The page opens but with the message "please restart chrome to run above flash". Has anyone got this to run successfully on flash based sites?

I am doing this on a Linux box ( EC2 instance ), all via the command line

**Comment by leonid-shevtsov** [comment]
Hi - apologies for answering so late, but this is not headless-related. My guess is that the EC2 instance does not have Flash installed, and if so, here's how to install it:

https://askubuntu.com/questions/341428/how-to-install-flash-player-on-ubuntu#341430
