### ISSUE TITLE
dimensions not the same as what I've set

### ISSUE THREAD

**Issue by map7** [leonid-shevtsov/headless#94]
I'm using headless gem on a Debian Jessie 64bit machine and when I set the dimensions and take a screenshot with Capybara-screenshot the dimensions in the screenshot are vastly different to what I've set in the headless gem.

```
  headless = Headless.new(dimensions: '1920x1200x24',
                          display: xvfb_port,
                          video: {
                            frame_rate: 12,
                            provider: :ffmpeg
                          })
```

Here are my results.
```
|     headless | screenshot |
|   dimensions |     result |
|--------------+------------|
| 1920x1200x24 |   1424x941 |
| 1920x1024x24 |   1424x941 |
| 1600x1200x42 |   1225x989 |
```

**Comment by leonid-shevtsov** [comment]
Hi - sorry for taking so long to respond - the Headless dimensions are like your monitor resolution and the screenshot is the size of the browser display area - without the window framing.

To get a screenshot of the size that you want, you'd need to add the window frame size to the headless dimensions.
